id: P003027
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12625
  title: བྱ་ཚིག་དུས་གསུམ་གྱི་རྣམ་བཞག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    be8a8ebede2c4912b253bd1d23fcc814:
      image_group_id: I1KG15013
      title: ''
      volume_number: 1
      total_pages: 106
