id: P003027
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG12625
  title: བྱ་ཚིག་དུས་གསུམ་གྱི་རྣམ་བཞག་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    be8a8ebede2c4912b253bd1d23fcc814:
      image_group_id: I1KG15013
      title: ''
      volume_number: 1
      total_pages: 106
      base_file: v001.txt
